### ISSUE TITLE
class colors errors and breaking list

### ISSUE THREAD

**Issue by Translitdk** [Mikeprod/FriendGroups#38]
`3x FriendGroups\FriendGroups-1.13_classic.lua:70: attempt to index local 'colour' (a nil value)
FriendGroups\FriendGroups-1.13_classic.lua:70: in function <FriendGroups\FriendGroups.lua:49>
FriendGroups\FriendGroups-1.13_classic.lua:156: in function <FriendGroups\FriendGroups.lua:88>
FriendGroups\FriendGroups-1.13_classic.lua:335: in function <FriendGroups\FriendGroups.lua:318>
FriendGroups\FriendGroups-1.13_classic.lua:711: in function <FriendGroups\FriendGroups.lua:420>
[C]: in function `FriendsList_Update'
FrameXML\FriendsFrame.lua:325: in function <FrameXML\FriendsFrame.lua:324>
[C]: in function `Show'
FrameXML\UIParent.lua:2078: in function `SetUIPanel'
FrameXML\UIParent.lua:1923: in function `ShowUIPanel'
FrameXML\UIParent.lua:1784: in function <FrameXML\UIParent.lua:1780>
[C]: in function `SetAttribute'
FrameXML\UIParent.lua:2526: in function `ShowUIPanel'
FrameXML\FriendsFrame.lua:1113: in function `ToggleFriendsFrame'
[string "TOGGLESOCIAL"]:1: in function <[string "TOGGLESOCIAL"]:1>

Locals:
class = ""
table = nil
initialClass = ""
colour = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = "|cFF%02x%02x%02x"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'colour' (a nil value)"`
had to add this for a while
[https://i.imgur.com/63s3XOH.png](url)

**Comment by Mikeprod** [comment]
It should have been fixed with todays release

**Comment by Translitdk** [comment]
https://i.imgur.com/47lgNi0.png
still have it somehow

**Comment by Translitdk** [comment]
might it be error if i'm on classic and someone online as DH/DK or smth?

**Comment by Mikeprod** [comment]
I will look into it ...

**Comment by Translitdk** [comment]
This happens on random when i open friend list. Might be someone online that causing it.

**Comment by Mikeprod** [comment]
Shloud be fixed with tonight's release. I will keep this issue open for a week or so if there is another mention of colour isssue

**Comment by Translitdk** [comment]
Just updated and got another error ;p Need to test w/o any other addons to make sure it is not coming from it. Or maybe my saved vars are corrupted

**Comment by mudohir** [comment]
> Shloud be fixed with tonight's release. I will keep this issue open for a week or so if there is another mention of colour isssue

I think the issue here is that the class is nil for DH/DK as mentioned before.  I tweaked the logic slightly to check for class instead of cooperation.   You can still have a DH/DK on the same faction.

I'll make a PR for the change shortly.

**Comment by mudohir** [comment]
> Just updated and got another error ;p Need to test w/o any other addons to make sure it is not coming from it. Or maybe my saved vars are corrupted
> 
> https://i.imgur.com/du5qlkR.png
> https://i.imgur.com/AWssuPY.png fixes it but still
> 
> --edit
> w/o any addon still the same, but i figured out https://i.imgur.com/dWA3aMc.png if this is disabled error appears. No error when enabled.

I made a fix for this - can you see if this fixes your issue?

**Comment by Mikeprod** [comment]
@mudohir could you please open pull request on the dev branch instead of master in the future please  ?

**Comment by mudohir** [comment]
> @mudohir could you please open pull request on the dev branch instead of master in the future please ?

Sure thing, sorry bout that.
